#!/bin/bash

# Since create-dmg does not override, be sure to delete previous DMG
test -f "output_name.dmg" && rm "output_name.dmg"

# Create the DMG
create-dmg/./create-dmg \
--hdiutil-quiet \
--volname "test" \
--volicon "volume.icns" \
--background "background.tiff" \
--window-pos 333 333 \
--window-size 500 380 \
--text-size 12 \
--icon-size 136 \
--icon "Test.app" 150 180 \
--hide-extension "Test.app" \
--app-drop-link 350 180 \
"output_name.dmg" \
"source_folder/"
